

/**
 * PLY4Loader
 * Loads .ply4 (Extended PLY with temporal banks) generated by extract_checkpoint_ply.py.
 * Converts per-vertex bank data into trajectory arrays compatible with 4DGS pipeline.
 */
export class PLY4Loader {

    async load(file: File, progressCallback?: (progress: number, message: string) => void): Promise<any> {
        progressCallback?.(0, "Reading PLY4");
        const buffer = await file.arrayBuffer();

        const text = new TextDecoder().decode(buffer.slice(0, 10000));
        const headerEnd = this.findHeaderEnd(buffer);
        const headerText = text.substring(0, headerEnd).toLowerCase(); // Case insensitive
        const lines = headerText.split('\n');

        // Parse Header
        let vertexCount = 0;
        const propertyTypes: { name: string, type: string, size: number }[] = [];
        const propOffsets: { [key: string]: number } = {};

        let currentElement = "";
        let offset = 0;
        let isLittleEndian = true; // Default PLY is usually little, but check format

        // Metadata extraction
        let xyz_bank_k_c = 0;
        let rot_bank_k_c = 0;
        let xyz_stride = 1;
        let rot_stride = 1;
        let total_frames = 0;

        for (const line of lines) {
            const parts = line.trim().split(/\s+/);
            if (parts[0] === 'format') {
                if (parts[1] === 'binary_big_endian') isLittleEndian = false;
            } else if (parts[0] === 'element') {
                currentElement = parts[1];
                if (currentElement === 'vertex') {
                    vertexCount = parseInt(parts[2]);
                }
            } else if (parts[0] === 'property') {
                if (currentElement === 'vertex') {
                    const type = parts[1];
                    const name = parts[2];

                    let size = 4; // Default float/int
                    if (type === 'double') size = 8;
                    if (type === 'uchar' || type === 'char') size = 1;
                    if (type === 'ushort' || type === 'short') size = 2;

                    propertyTypes.push({ name, type, size });
                    propOffsets[name] = offset;
                    offset += size;
                }
            } else if (parts[0] === 'comment') {
                // Parse custom comments
                // Check "total_frames 300"
                if (parts[1] === 'total_frames') total_frames = parseInt(parts[2]);
                if (parts[1] === 'xyz_bank_keyframe_stride') xyz_stride = parseInt(parts[2]);
                if (parts[1] === 'rot_bank_keyframe_stride') rot_stride = parseInt(parts[2]);

                // Fallback for "xyz_bank_k_c: 16" style just in case
                const content = line.substring(8).trim();
                if (content.startsWith('xyz_bank_k_c')) xyz_bank_k_c = parseInt(content.split(':')[1]);
                if (content.startsWith('rot_bank_k_c')) rot_bank_k_c = parseInt(content.split(':')[1]);
            }
        }

        // Infer K from properties if not found in comments
        if (xyz_bank_k_c === 0) {
            let maxK = -1;
            propertyTypes.forEach(p => {
                if (p.name.startsWith('xyz_bank_')) {
                    const parts = p.name.split('_');
                    if (parts.length >= 4) {
                        const k = parseInt(parts[2]);
                        if (!isNaN(k) && k > maxK) maxK = k;
                    }
                }
            });
            if (maxK !== -1) xyz_bank_k_c = maxK + 1;
        }

        if (rot_bank_k_c === 0) {
            let maxK = -1;
            propertyTypes.forEach(p => {
                if (p.name.startsWith('rot_bank_')) {
                    const parts = p.name.split('_');
                    if (parts.length >= 4) {
                        const k = parseInt(parts[2]);
                        if (!isNaN(k) && k > maxK) maxK = k;
                    }
                }
            });
            if (maxK !== -1) rot_bank_k_c = maxK + 1;
        }




        console.log(`[PLY4] Count: ${vertexCount}, XYZ_K: ${xyz_bank_k_c}, ROT_K: ${rot_bank_k_c}`);

        // Read Binary Body
        const bodyStart = headerEnd;
        const view = new DataView(buffer);
        // Note: DataView starts at 0, so we use absolute offsets.

        const rowSize = propertyTypes.reduce((sum, p) => sum + p.size, 0);
        const expectedSize = bodyStart + vertexCount * rowSize;
        console.log(`[PLY4] VertexCount: ${vertexCount}, RowSize: ${rowSize}, Expected Total Size: ${expectedSize}`);

        if (buffer.byteLength < expectedSize) {
            console.error(`[PLY4] Buffer too small! Missing ${expectedSize - buffer.byteLength} bytes.`);
            // Proceeding might crash, but let's try to read what we can or just truncate count
        }


        // Prepare Destination Arrays
        // Static
        const x = new Float32Array(vertexCount);
        const y = new Float32Array(vertexCount);
        const z = new Float32Array(vertexCount);

        const rot_0 = new Float32Array(vertexCount);
        const rot_1 = new Float32Array(vertexCount);
        const rot_2 = new Float32Array(vertexCount);
        const rot_3 = new Float32Array(vertexCount);

        const opacity = new Float32Array(vertexCount);
        const scale_0 = new Float32Array(vertexCount);
        const scale_1 = new Float32Array(vertexCount);
        const scale_2 = new Float32Array(vertexCount);

        const f_dc_0 = new Float32Array(vertexCount);
        const f_dc_1 = new Float32Array(vertexCount);
        const f_dc_2 = new Float32Array(vertexCount);

        // Lifetime
        const lifetime_mu = new Float32Array(vertexCount);
        const lifetime_w = new Float32Array(vertexCount);
        const lifetime_k = new Float32Array(vertexCount); // Will default to 10 if not found
        // SOG4 style
        const t_start = new Float32Array(vertexCount);
        const duration = new Float32Array(vertexCount);

        // SH (rest)
        const sh_rest: Float32Array[] = [];
        for (let i = 0; i < 45; i++) {
            // Only alloc if property exists to save ram
            if (propOffsets[`f_rest_${i}`] !== undefined) sh_rest[i] = new Float32Array(vertexCount);
        }

        // Dynamic Banks
        // We will flatten them into the trajectory format used by SOG4/TrueSplats
        // SOG4 Format: Float32Array(N * K * 3)
        // Interleaved: Point0_K0, Point0_K1... (This matches the PLY row layout perfectly actually!)
        // Wait, PLY row has: x, y, z, ... bank0_x, bank0_y, bank0_z ...
        // So for each POINT, we have ALL its keyframes contiguously? 
        // YES.

        // However, standard SOG4 trajectory array is monolithic: [x0k0, y0k0, z0k0, x0k1... x1k0...]
        // So we can write directly as we iterate rows.

        const xyzData = xyz_bank_k_c > 0 ? new Float32Array(vertexCount * xyz_bank_k_c * 3) : null;
        const rotData = rot_bank_k_c > 0 ? new Float32Array(vertexCount * rot_bank_k_c * 4) : null;

        const getFloat = (name: string, rowBase: number) => {
            if (propOffsets[name] === undefined) return 0;
            const offset = rowBase + propOffsets[name];
            if (offset + 4 > buffer.byteLength) {
                // console.warn(`[PLY4] OOB Read for ${name} at ${offset}`);
                return 0;
            }
            return view.getFloat32(offset, isLittleEndian);
        };

        const sigmoid = (v: number) => 1.0 / (1.0 + Math.exp(-v));

        let pct = 0;
        for (let i = 0; i < vertexCount; i++) {
            const rowBase = bodyStart + i * rowSize;

            // Progress update
            if (i % 10000 === 0) {
                const p = Math.floor((i / vertexCount) * 100);
                if (p > pct) {
                    pct = p;
                    progressCallback?.(pct, `Parsing Vertex ${i}/${vertexCount}`);
                }
            }

            // Static
            x[i] = getFloat('x', rowBase);
            y[i] = getFloat('y', rowBase);
            z[i] = getFloat('z', rowBase);

            rot_0[i] = getFloat('rot_0', rowBase);
            rot_1[i] = getFloat('rot_1', rowBase);
            rot_2[i] = getFloat('rot_2', rowBase);
            rot_3[i] = getFloat('rot_3', rowBase);

            scale_0[i] = getFloat('scale_0', rowBase);
            scale_1[i] = getFloat('scale_1', rowBase);
            scale_2[i] = getFloat('scale_2', rowBase);

            opacity[i] = sigmoid(getFloat('opacity', rowBase)); // PLY usually stores logit

            f_dc_0[i] = getFloat('f_dc_0', rowBase);
            f_dc_1[i] = getFloat('f_dc_1', rowBase);
            f_dc_2[i] = getFloat('f_dc_2', rowBase);

            if (propOffsets['lifetime_mu'] !== undefined) lifetime_mu[i] = getFloat('lifetime_mu', rowBase);
            if (propOffsets['lifetime_w'] !== undefined) lifetime_w[i] = getFloat('lifetime_w', rowBase);
            if (propOffsets['lifetime_k'] !== undefined) lifetime_k[i] = getFloat('lifetime_k', rowBase);
            else lifetime_k[i] = 10.0;

            // Compute t_start/dur for SOG logic (optional but good for compatibility)
            t_start[i] = lifetime_mu[i] - lifetime_w[i];
            duration[i] = 2.0 * lifetime_w[i];

            // SH Rest
            for (let j = 0; j < 45; j++) {
                if (sh_rest[j]) sh_rest[j][i] = getFloat(`f_rest_${j}`, rowBase);
            }

            // Dynamic Banks
            // Properties are named: xyz_bank_0_0 (bank 0, comp 0/x), xyz_bank_0_1 (y), etc.
            if (xyzData) {
                for (let k = 0; k < xyz_bank_k_c; k++) {
                    const bx = getFloat(`xyz_bank_${k}_x`, rowBase);
                    const by = getFloat(`xyz_bank_${k}_y`, rowBase);
                    const bz = getFloat(`xyz_bank_${k}_z`, rowBase);

                    const base = i * xyz_bank_k_c * 3 + k * 3;
                    xyzData[base + 0] = bx;
                    xyzData[base + 1] = by;
                    xyzData[base + 2] = bz;
                }
            }
            if (rotData) {
                for (let k = 0; k < rot_bank_k_c; k++) {
                    const br = getFloat(`rot_bank_${k}_x`, rowBase); // x
                    const bg = getFloat(`rot_bank_${k}_y`, rowBase); // y
                    const bb = getFloat(`rot_bank_${k}_z`, rowBase); // z
                    const ba = getFloat(`rot_bank_${k}_w`, rowBase); // w

                    // SOG/TrueSplats usually expects quaternion.
                    // Assuming bank stores raw quaternion components.
                    const base = i * rot_bank_k_c * 4 + k * 4;
                    // Shader quatToMat3 expects q to be (x, y, z, w).
                    // PLY properties are explicit (x, y, z, w).
                    rotData[base + 0] = br; // x
                    rotData[base + 1] = bg; // y
                    rotData[base + 2] = bb; // z
                    rotData[base + 3] = ba; // w
                }
            }

        }

        // Fallback for total_frames if not found
        if (total_frames === 0 && xyz_bank_k_c > 0) {
            total_frames = xyz_bank_k_c * xyz_stride;
        }

        // Construct Result Object compatible with GSplatResource/TrueSplatsLoader

        // plyData structure for constructing GSplatData
        const plyProperties: any[] = [
            { name: 'x', type: 'float', storage: x },
            { name: 'y', type: 'float', storage: y },
            { name: 'z', type: 'float', storage: z },
            { name: 'rot_0', type: 'float', storage: rot_0 },
            { name: 'rot_1', type: 'float', storage: rot_1 },
            { name: 'rot_2', type: 'float', storage: rot_2 },
            { name: 'rot_3', type: 'float', storage: rot_3 },
            { name: 'scale_0', type: 'float', storage: scale_0 },
            { name: 'scale_1', type: 'float', storage: scale_1 },
            { name: 'scale_2', type: 'float', storage: scale_2 },
            { name: 'opacity', type: 'float', storage: opacity },
            { name: 'f_dc_0', type: 'float', storage: f_dc_0 },
            { name: 'f_dc_1', type: 'float', storage: f_dc_1 },
            { name: 'f_dc_2', type: 'float', storage: f_dc_2 },
            { name: 'lifetime_mu', type: 'float', storage: lifetime_mu },
            { name: 'lifetime_w', type: 'float', storage: lifetime_w },
        ];

        for (let j = 0; j < 45; j++) {
            if (sh_rest[j]) plyProperties.push({ name: `f_rest_${j}`, type: 'float', storage: sh_rest[j] });
        }

        const plyData = {
            elements: [{
                name: 'vertex',
                count: vertexCount,
                properties: plyProperties
            }]
        };

        return {
            count: vertexCount,
            plyData: plyData,

            // Dynamic Data
            is4DGS: (xyz_bank_k_c > 0 || rot_bank_k_c > 0),
            frames: total_frames,
            keyframes: xyz_bank_k_c,
            rotKeyframes: rot_bank_k_c,
            xyzStride: xyz_stride,
            rotStride: rot_stride,

            trajectory: xyzData,
            rotTrajectory: rotData,

            // Allow export to pass through
            bands: 3 // Default
        };
    }

    private findHeaderEnd(buffer: ArrayBuffer): number {
        const view = new Uint8Array(buffer);
        const searchLen = Math.min(10000, view.length); // Search first 10KB
        const decoder = new TextDecoder('ascii');
        const text = decoder.decode(view.slice(0, searchLen));

        const idx = text.indexOf('end_header');
        if (idx !== -1) {
            // Find the newline after end_header
            let newlineIdx = idx + 10; // skip 'end_header'
            while (newlineIdx < searchLen && text.charCodeAt(newlineIdx) !== 10) { // 10 is \n
                newlineIdx++;
            }
            if (newlineIdx < searchLen) {
                return newlineIdx + 1; // Return index AFTER \n
            }
        }

        // Fallback: manual search if chunk was too small? 
        // Unlikely for PLY header.
        console.error("[PLY4] Could not find end_header!");
        return 0;
    }
}
