import argparse
import numpy as np
from plyfile import PlyData

def compare_ply_files(file1, file2, tolerance=1e-4):
    print(f"Comparing:\\n  [1] {file1}\\n  [2] {file2}")
    
    ply1 = PlyData.read(file1)
    ply2 = PlyData.read(file2)
    
    v1 = ply1['vertex']
    v2 = ply2['vertex']
    
    if v1.count != v2.count:
        print(f"❌ Vertex count mismatch! File1: {v1.count}, File2: {v2.count}")
        return False
    
    print(f"✅ Vertex count match: {v1.count}")
    
    prop_names1 = [p.name for p in v1.properties]
    prop_names2 = [p.name for p in v2.properties]
    
    if set(prop_names1) != set(prop_names2):
        print("❌ Property names mismatch!")
        print(f"Only in 1: {set(prop_names1) - set(prop_names2)}")
        print(f"Only in 2: {set(prop_names2) - set(prop_names1)}")
    else:
        print("✅ Property structures match")
    
    all_match = True
    max_err = 0.0
    worst_prop = ""
    
    # Compare all overlapping properties
    common_props = set(prop_names1).intersection(set(prop_names2))
    for prop in common_props:
        arr1 = np.asarray(v1[prop])
        arr2 = np.asarray(v2[prop])
        
        diff = np.abs(arr1 - arr2)
        err = np.max(diff)
        if err > max_err:
            max_err = err
            worst_prop = prop
            
        if err > tolerance:
            print(f"❌ Property '{prop}' exceeds tolerance {tolerance} (Max error: {err:.6f})")
            
            # Print a few samples where it fails
            bad_idx = np.where(diff > tolerance)[0]
            print(f"   ({len(bad_idx)} values differ out of {v1.count})")
            for i in bad_idx[:3]:
                print(f"   [{i}] f1: {arr1[i]:.6f}, f2: {arr2[i]:.6f}")
                
            all_match = False
    
    if all_match:
        print(f"✅ All properties match within tolerance {tolerance}! (Max err: {max_err:.6f} on {worst_prop})")
    return all_match

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("file1", help="Generated by python")
    parser.add_argument("file2", help="Generated by typescript")
    parser.add_argument("--tol", type=float, default=1e-4, help="Tolerance for float precision differences")
    args = parser.parse_args()
    
    compare_ply_files(args.file1, args.file2, args.tol)
